import asyncio
import aiohttp
import requests

API_URL = "http://127.0.0.1:8000/report"

# ✅ Your dataset (example structure — replace with your real list)
reports_data = [
    {
        "id": "9de93e77-c6cf-4432-b298-5518efaa225c",
        "city": "Hyderabad",
        "timestamp": "2025-08-24T22:20:58.320608",
        "rating": 4,
        "comment": "The **voltage fluctuations** in Hyderabad are severe, causing my fan to slow down and lights to flicker. I'm worried about my AC.",
        "public_service": "Electricity",
        "district": "Hyderabad",
        "device_location": "17.4198,78.4958",
        "is_anonymous": False,
        "name": "Divya Menon",
        "gender": "Female",
        "age": 55,
        "imgUrl": "https://example.com/images/21c905dd-f91b-4ba1-ae28-83b70c26f28a.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "e417057c-7d05-43ac-ad30-cad6c2745cd8",
        "city": "Pune",
        "timestamp": "2025-10-23T20:45:58.320904",
        "rating": 5,
        "comment": "Great work by the **Street Lights** team in Pune! The entire stretch of the highway has new, bright, and working lights.",
        "public_service": "Street Lights",
        "district": "Pune",
        "device_location": "18.5403,73.8301",
        "is_anonymous": False,
        "name": "Gaurav Jain",
        "gender": "Male",
        "age": 26,
        "imgUrl": "https://example.com/images/ac910cd2-5db3-4bb9-b364-fe5ec4727f60.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "866376a1-4210-4bfc-84d5-92324db978f7",
        "city": "Bengaluru",
        "timestamp": "2025-08-28T17:09:58.321519",
        "rating": 5,
        "comment": "The **traffic jam** in Bengaluru near the metro construction site is persistent and lasts for hours. Proper diversion plans are needed.",
        "public_service": "Traffic Management",
        "district": "Bengaluru",
        "device_location": "12.9563,77.5641",
        "is_anonymous": False,
        "name": "Ravi Kumar",
        "gender": "Other",
        "age": 38,
        "imgUrl": "https://example.com/images/b98ed128-d39c-4f67-9f4d-d4f0adcc1033.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "83d20b7e-46ce-4416-8b58-c3b72ff04182",
        "city": "Kolkata",
        "timestamp": "2025-05-01T05:40:58.322057",
        "rating": 4,
        "comment": "I reported a **non-functional street light** in Kolkata yesterday, and it was fixed today. Very fast and effective service.",
        "public_service": "Street Lights",
        "district": "Kolkata",
        "device_location": "22.6064,88.4009",
        "is_anonymous": False,
        "name": "Sneha Patel",
        "gender": "Female",
        "age": 61,
        "imgUrl": "https://example.com/images/de5a2307-249b-4803-8f28-e9c8bb33a9ce.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "38f82679-ab96-4375-b817-cb3b542cf269",
        "city": "Ahmedabad",
        "timestamp": "2025-06-29T09:11:58.322740",
        "rating": 5,
        "comment": "Near the market area, the road is broken and full of **potholes**. It looks like a crater field! Urgently needs resurfacing in Ahmedabad.",
        "public_service": "Road Maintenance",
        "district": "Ahmedabad",
        "device_location": "23.0087,72.542",
        "is_anonymous": False,
        "name": "Neha Thakur",
        "gender": "Female",
        "age": 47,
        "imgUrl": "https://example.com/images/d88f08ae-9e73-4906-aec8-91efec2ca3cd.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1670727d-9199-4568-abea-445cf2f2d156",
        "city": "Hyderabad",
        "timestamp": "2025-06-21T23:22:58.323144",
        "rating": 4,
        "comment": "The **traffic jam** in Hyderabad near the metro construction site is persistent and lasts for hours. Proper diversion plans are needed.",
        "public_service": "Traffic Management",
        "district": "Hyderabad",
        "device_location": "17.3387,78.4544",
        "is_anonymous": False,
        "name": "Kiran Reddy",
        "gender": "Female",
        "age": 31,
        "imgUrl": "https://example.com/images/97fedf00-2fef-41ed-80b7-f4ef8e0d82c1.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "6355c54a-5cc6-4254-a7a5-0b3396f8b566",
        "city": "Mumbai",
        "timestamp": "2025-08-02T02:21:58.323541",
        "rating": 4,
        "comment": "The Mumbai **city buses** are almost always **delayed**, making it difficult for daily commuters to reach on time.",
        "public_service": "Public Transport",
        "district": "Mumbai",
        "device_location": "19.0483,72.8452",
        "is_anonymous": False,
        "name": "Ravi Kumar",
        "gender": "Other",
        "age": 27,
        "imgUrl": "https://example.com/images/6dbc1c6e-e821-4886-9d1c-7215d6aa6f09.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "8656311a-f672-4841-b10e-30888228e101",
        "city": "Bengaluru",
        "timestamp": "2025-01-11T15:53:58.323892",
        "rating": 4,
        "comment": "The **water supply** in Bengaluru has been highly **inconsistent**. We often get water only for a short time in the morning, making it impossible to manage daily chores. A fixed schedule is urgently needed.",
        "public_service": "Water Supply",
        "district": "Bengaluru",
        "device_location": "12.9304,77.5661",
        "is_anonymous": False,
        "name": "Suresh Nair",
        "gender": "Male",
        "age": 42,
        "imgUrl": "https://example.com/images/9d375fd5-9411-4f27-887b-6c5dce312bcf.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "862dfdc8-f36b-498e-8779-b03e8692aca5",
        "city": "Hyderabad",
        "timestamp": "2025-04-07T07:20:58.324254",
        "rating": 5,
        "comment": "The **signal timing** at the stadium junction in Hyderabad is completely wrong. The main road signal is too short during rush hour.",
        "public_service": "Traffic Management",
        "district": "Hyderabad",
        "device_location": "17.3398,78.5025",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/fcbe16c3-6bc4-41e0-b31e-a2a4ab625eb0.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "945b0963-c7ab-441e-96d3-f1c87fcfd90a",
        "city": "Mumbai",
        "timestamp": "2025-03-09T13:15:58.324580",
        "rating": 4,
        "comment": "There is a major **pipe leak** near the main road in Mumbai, leading to huge wastage of water. It's been running for two days.",
        "public_service": "Water Supply",
        "district": "Mumbai",
        "device_location": "19.0626,72.8425",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/326ee896-46fa-4685-8906-70d93d502be3.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "fcd16ee2-b936-42ae-82b5-649f4a2c8f32",
        "city": "Hyderabad",
        "timestamp": "2025-09-01T06:54:58.324858",
        "rating": 5,
        "comment": "The **garbage collection** in Hyderabad has become highly irregular. Sometimes they miss entire weeks, causing huge piles of waste.",
        "public_service": "Garbage Collection",
        "district": "Hyderabad",
        "device_location": "17.3639,78.4786",
        "is_anonymous": False,
        "name": "Meera Hegde",
        "gender": "Other",
        "age": 36,
        "imgUrl": "https://example.com/images/03b95251-e888-455e-97d3-d5a9750a7196.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "cd00fb80-03b0-42f7-9ca1-ebc8f1896fe2",
        "city": "Chennai",
        "timestamp": "2025-05-09T09:40:58.325133",
        "rating": 4,
        "comment": "Appreciate the regular maintenance of **street lights** in the residential blocks of Chennai. Good consistency.",
        "public_service": "Street Lights",
        "district": "Chennai",
        "device_location": "13.0435,80.2269",
        "is_anonymous": False,
        "name": "Rohit Khanna",
        "gender": "Female",
        "age": 45,
        "imgUrl": "https://example.com/images/d374f6af-851f-4a79-971e-0a18748c0994.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "4f7f4d71-bb1c-4e74-8768-db75fa1134e7",
        "city": "Delhi",
        "timestamp": "2025-04-04T16:23:58.325413",
        "rating": 5,
        "comment": "The **frequent power cuts** are damaging our electronic devices in Delhi. Compensation or better maintenance is required.",
        "public_service": "Electricity",
        "district": "Delhi",
        "device_location": "28.7273,77.1007",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Other",
        "age": 32,
        "imgUrl": "https://example.com/images/36b83e12-ae92-4568-afa5-33aab860d669.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "817ee2c1-0520-439d-b5f3-6f59d018605c",
        "city": "Bengaluru",
        "timestamp": "2025-02-27T03:19:58.325726",
        "rating": 4,
        "comment": "The **water quality** in Bengaluru is poor; it's often muddy and has a strange odour, raising health concerns. Please check for pipeline contamination.",
        "public_service": "Water Supply",
        "district": "Bengaluru",
        "device_location": "12.9558,77.6131",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Other",
        "age": 42,
        "imgUrl": "https://example.com/images/fb166f86-96be-4b26-8b2a-b57bbd3a5930.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1005fe30-0ae5-4cb1-802a-0cc728076b66",
        "city": "Ahmedabad",
        "timestamp": "2024-11-11T05:14:58.325992",
        "rating": 4,
        "comment": "We've been getting consistent and timely **garbage collection** in Ahmedabad for the last few months. Excellent service!",
        "public_service": "Garbage Collection",
        "district": "Ahmedabad",
        "device_location": "23.0685,72.5953",
        "is_anonymous": False,
        "name": "Ravi Kumar",
        "gender": "Male",
        "age": 43,
        "imgUrl": "https://example.com/images/de8c72d2-c03c-4447-b2a5-782f08837d50.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "6e20f6d3-00b7-4eb2-897c-5d23aa655d90",
        "city": "Chennai",
        "timestamp": "2024-11-09T16:43:58.326264",
        "rating": 5,
        "comment": "Thanks to the Chennai **Electricity** team for the quick response during the night-time blackout. Power restored in an hour.",
        "public_service": "Electricity",
        "district": "Chennai",
        "device_location": "13.1129,80.235",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/88930f85-192e-407e-99f1-9be1c22a103e.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "41339af0-d151-4aaf-b798-abec22f788ff",
        "city": "Kolkata",
        "timestamp": "2025-03-26T23:27:58.326615",
        "rating": 4,
        "comment": "The **power has been off** since morning in Kolkata. The complaint line is constantly busy. Please resolve it.",
        "public_service": "Public Transport",
        "district": "Kolkata",
        "device_location": "22.5681,88.3407",
        "is_anonymous": False,
        "name": "Lata Joshi",
        "gender": "Other",
        "age": 42,
        "imgUrl": "https://example.com/images/671e9835-e143-42e0-b42b-eebc35813c78.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "c42a4cf3-6631-4087-b7db-fc7894bce582",
        "city": "Hyderabad",
        "timestamp": "2025-05-19T18:45:58.327170",
        "rating": 5,
        "comment": "Driving on the highway through Hyderabad is a nightmare because of the constant bumps and **uneven road surfaces**. Please ensure a smooth drive.",
        "public_service": "Road Maintenance",
        "district": "Hyderabad",
        "device_location": "17.3645,78.4744",
        "is_anonymous": False,
        "name": "Kiran Reddy",
        "gender": "Female",
        "age": 18,
        "imgUrl": "https://example.com/images/1a12c258-6fe4-4fab-88ce-94a8d38ecadf.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "64da1fc1-5c93-4d33-a89a-5e3f6c9b3f2d",
        "city": "Chennai",
        "timestamp": "2024-12-23T20:22:58.327493",
        "rating": 4,
        "comment": "Water pressure drops drastically every evening in Chennai. This needs a permanent investigation and repair.",
        "public_service": "Water Supply",
        "district": "Chennai",
        "device_location": "13.0627,80.2217",
        "is_anonymous": False,
        "name": "Samrat Ghosh",
        "gender": "Other",
        "age": 39,
        "imgUrl": "https://example.com/images/2bf7bf44-e42d-4d5a-8f2d-af69a9d48efd.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d053256b-a0e5-40f0-8a26-23c76dfcb868",
        "city": "Pune",
        "timestamp": "2024-12-06T02:18:58.328030",
        "rating": 4,
        "comment": "The temporary filling of the **potholes** in Pune didn't last a week. We need a proper, permanent solution.",
        "public_service": "Road Maintenance",
        "district": "Pune",
        "device_location": "18.5632,73.8919",
        "is_anonymous": False,
        "name": "Rohit Khanna",
        "gender": "Male",
        "age": 46,
        "imgUrl": "https://example.com/images/c524504a-273b-493c-a001-eccf316924ac.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "12b3430c-68b3-4123-a37f-83d5becd23c0",
        "city": "Kolkata",
        "timestamp": "2025-10-22T05:17:58.328297",
        "rating": 4,
        "comment": "It's shocking how many **non-functional street lights** there are on the main bypass road in Kolkata. Please replace them.",
        "public_service": "Street Lights",
        "district": "Kolkata",
        "device_location": "22.5614,88.3686",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Female",
        "age": 39,
        "imgUrl": "https://example.com/images/8ce9880f-552b-49c3-b26d-a200084ee124.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "2fc6bc38-8fa4-40f9-8d1a-f106b0c49a9c",
        "city": "Hyderabad",
        "timestamp": "2024-11-14T06:52:58.328636",
        "rating": 4,
        "comment": "Frequent **cancellation** of the main express bus line in Hyderabad forces us to take expensive alternatives. Please prioritize the service.",
        "public_service": "Public Transport",
        "district": "Hyderabad",
        "device_location": "17.4019,78.4534",
        "is_anonymous": False,
        "name": "Manoj Iyer",
        "gender": "Male",
        "age": 39,
        "imgUrl": "https://example.com/images/e1cadc86-d835-49c9-8aea-e8e165b85130.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "2cfdf7c7-6a5c-4889-940c-4531b5ffbe58",
        "city": "Pune",
        "timestamp": "2025-04-08T19:16:58.328963",
        "rating": 5,
        "comment": "The **traffic signal** at the main crossing in Pune has been broken for 3 days, causing massive confusion and near accidents.",
        "public_service": "Traffic Management",
        "district": "Pune",
        "device_location": "18.5597,73.8372",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/69cbe540-06bf-4886-9f6d-0b7b3dcb0863.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "7056e185-01fe-474a-b6c2-983cd1af456d",
        "city": "Pune",
        "timestamp": "2025-07-18T21:33:58.329267",
        "rating": 4,
        "comment": "Every evening, precisely at 7 PM, the power goes out in Pune. The **load shedding** is completely unacceptable.",
        "public_service": "Electricity",
        "district": "Pune",
        "device_location": "18.5514,73.8123",
        "is_anonymous": False,
        "name": "Amit Sharma",
        "gender": "Other",
        "age": 39,
        "imgUrl": "https://example.com/images/87602d77-bea1-453c-b368-117021751abc.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "c2320928-9ae6-44b0-b5c8-d9ca4f635388",
        "city": "Kolkata",
        "timestamp": "2025-02-18T08:18:58.329952",
        "rating": 5,
        "comment": "Driving on the highway through Kolkata is a nightmare because of the constant bumps and **uneven road surfaces**. Please ensure a smooth drive.",
        "public_service": "Road Maintenance",
        "district": "Kolkata",
        "device_location": "22.5515,88.3421",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Female",
        "age": 53,
        "imgUrl": "https://example.com/images/c192bd78-5414-44f4-b37e-d05130e40316.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "bb7edc7d-c3c2-4096-96ac-a93dc2bcd839",
        "city": "Chennai",
        "timestamp": "2025-09-17T20:17:58.330499",
        "rating": 4,
        "comment": "The **garbage collection** in Chennai has become highly irregular. Sometimes they miss entire weeks, causing huge piles of waste.",
        "public_service": "Garbage Collection",
        "district": "Chennai",
        "device_location": "13.095,80.272",
        "is_anonymous": False,
        "name": "Isha Sharma",
        "gender": "Female",
        "age": 57,
        "imgUrl": "https://example.com/images/6e2581b0-699b-42da-83b6-ed7ccb5b60ad.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "3f6f2b5f-32e2-4698-b024-d931e9b791ff",
        "city": "Delhi",
        "timestamp": "2025-08-17T04:08:58.330858",
        "rating": 4,
        "comment": "There is a major **pipe leak** near the main road in Delhi, leading to huge wastage of water. It's been running for two days.",
        "public_service": "Water Supply",
        "district": "Delhi",
        "device_location": "28.7493,77.1318",
        "is_anonymous": False,
        "name": "Ravi Kumar",
        "gender": "Other",
        "age": 22,
        "imgUrl": "https://example.com/images/59bb1de3-8927-4315-b40f-3cb3a62b30fa.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "82c9299c-d73c-4020-8fef-aedaffceac4c",
        "city": "Chennai",
        "timestamp": "2025-06-24T19:00:58.331389",
        "rating": 4,
        "comment": "The recently maintained roads in the residential areas of Chennai are excellent. A smooth commute, thank you **Road Maintenance**!",
        "public_service": "Road Maintenance",
        "district": "Chennai",
        "device_location": "13.0613,80.32",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/72dc15e9-6085-4235-863f-e04821babeee.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "f6fdbf28-d4bb-45da-a2b3-8d549ec33d74",
        "city": "Bengaluru",
        "timestamp": "2025-03-04T23:48:58.331886",
        "rating": 4,
        "comment": "The temporary filling of the **potholes** in Bengaluru didn't last a week. We need a proper, permanent solution.",
        "public_service": "Road Maintenance",
        "district": "Bengaluru",
        "device_location": "13.017,77.6382",
        "is_anonymous": False,
        "name": "Meera Hegde",
        "gender": "Other",
        "age": 46,
        "imgUrl": "https://example.com/images/1925c7c3-9103-40bb-ad51-975a1ffb327c.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "ae71c556-6d8e-42d1-9ae4-85e4e9e88786",
        "city": "Chennai",
        "timestamp": "2025-03-19T00:05:58.332151",
        "rating": 4,
        "comment": "It seems the route for **garbage collection** has changed in Chennai without any notification. Need clarity on the new schedule.",
        "public_service": "Garbage Collection",
        "district": "Chennai",
        "device_location": "13.0432,80.3197",
        "is_anonymous": False,
        "name": "Zakir Hussain",
        "gender": "Other",
        "age": 56,
        "imgUrl": "https://example.com/images/b441685d-7bd2-4841-a2ac-e8e6b841fca4.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "80368e0b-0bd6-497a-b82e-80a0715172fb",
        "city": "Pune",
        "timestamp": "2025-01-22T02:00:58.332645",
        "rating": 4,
        "comment": "The main road in Pune is absolutely riddled with **potholes**. It's a risk for two-wheelers and drivers need to swerve dangerously.",
        "public_service": "Road Maintenance",
        "district": "Pune",
        "device_location": "18.4844,73.8301",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Female",
        "age": 34,
        "imgUrl": "https://example.com/images/cb6bcc7c-24bb-48ec-a050-206fb606dd0e.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "b12eba6b-2c50-4447-b22e-e75e7bb9a517",
        "city": "Chennai",
        "timestamp": "2025-02-11T06:00:58.332899",
        "rating": 4,
        "comment": "The **frequent power cuts** are damaging our electronic devices in Chennai. Compensation or better maintenance is required.",
        "public_service": "Electricity",
        "district": "Chennai",
        "device_location": "13.1018,80.3065",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/954833d5-72af-424d-830e-74e8b4e867b1.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "dac7f956-3eae-40d1-af74-0fe67c7267d2",
        "city": "Ahmedabad",
        "timestamp": "2025-10-23T03:50:58.333213",
        "rating": 4,
        "comment": "The new fleet of buses in Ahmedabad is excellent, but the **timings need to be strictly followed**.",
        "public_service": "Public Transport",
        "district": "Ahmedabad",
        "device_location": "23.0042,72.5319",
        "is_anonymous": False,
        "name": "Anjali Singh",
        "gender": "Male",
        "age": 50,
        "imgUrl": "https://example.com/images/6aa2ee97-5ba5-4fe1-9ff7-17727dee93ec.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1879c4e8-271e-459c-8807-a760658e5d9e",
        "city": "Delhi",
        "timestamp": "2025-10-17T07:00:58.333459",
        "rating": 5,
        "comment": "Timely **garbage collection** is key to a clean city, and Delhi has been delivering that lately. Good progress.",
        "public_service": "Garbage Collection",
        "district": "Delhi",
        "device_location": "28.7293,77.0647",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Other",
        "age": 27,
        "imgUrl": "https://example.com/images/8546aaa6-6a22-41b9-aa4c-59eebcdc0aac.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "b5132f37-1a58-44e2-b3bf-622f02fe66fb",
        "city": "Ahmedabad",
        "timestamp": "2025-03-08T09:37:58.333734",
        "rating": 4,
        "comment": "Great improvement in **water supply** this month! The timing is much more predictable now. Keep up the good work in Ahmedabad.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "22.9997,72.5494",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Female",
        "age": 64,
        "imgUrl": "https://example.com/images/292b7848-f0c1-42cf-af91-02bfb7acf9d3.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "a0b6b639-bb99-4739-92c5-f1859c7430e1",
        "city": "Chennai",
        "timestamp": "2025-02-03T06:50:58.333962",
        "rating": 4,
        "comment": "The local **dumping ground** near Chennai is badly managed. The garbage is strewn everywhere, and stray dogs are a menace.",
        "public_service": "Garbage Collection",
        "district": "Chennai",
        "device_location": "13.0895,80.2972",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/008e22a5-2bba-41c3-873b-db965a731fd1.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "e461086b-4fcc-4e26-9041-e004a460fdec",
        "city": "Pune",
        "timestamp": "2025-03-22T18:25:58.334252",
        "rating": 5,
        "comment": "The **traffic signal** works perfectly now in Pune. No more unnecessary waiting periods.",
        "public_service": "Traffic Management",
        "district": "Pune",
        "device_location": "18.4787,73.9052",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Male",
        "age": 65,
        "imgUrl": "https://example.com/images/83cf7d4b-0b19-443a-9690-a5f150a0d972.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "a7de5468-a959-4add-a83e-dd9670854e3d",
        "city": "Hyderabad",
        "timestamp": "2025-01-19T13:54:58.334485",
        "rating": 5,
        "comment": "The local **dumping ground** near Hyderabad is badly managed. The garbage is strewn everywhere, and stray dogs are a menace.",
        "public_service": "Garbage Collection",
        "district": "Hyderabad",
        "device_location": "17.4096,78.4606",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Other",
        "age": 61,
        "imgUrl": "https://example.com/images/5280b0f9-7c64-4ad3-8414-ba4c049ac055.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d2ee2f44-8cd0-416b-8e31-787abe0f0255",
        "city": "Hyderabad",
        "timestamp": "2025-06-16T15:26:58.334705",
        "rating": 4,
        "comment": "The local **dumping ground** near Hyderabad is badly managed. The garbage is strewn everywhere, and stray dogs are a menace.",
        "public_service": "Garbage Collection",
        "district": "Hyderabad",
        "device_location": "17.3772,78.5158",
        "is_anonymous": False,
        "name": "Sneha Patel",
        "gender": "Male",
        "age": 51,
        "imgUrl": "https://example.com/images/d685d528-cade-4ad3-ba57-48cfd864b749.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "0204edd0-7a2c-4510-892c-c2d8c143bd07",
        "city": "Ahmedabad",
        "timestamp": "2025-08-22T09:52:58.334930",
        "rating": 4,
        "comment": "The **power supply** has been remarkably stable in Ahmedabad over the last six months. Excellent job by the Electricity department.",
        "public_service": "Electricity",
        "district": "Ahmedabad",
        "device_location": "23.0705,72.5725",
        "is_anonymous": False,
        "name": "Lata Joshi",
        "gender": "Female",
        "age": 61,
        "imgUrl": "https://example.com/images/baf45774-7031-4191-8ce8-7ebe133fd68b.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "cddb5f40-360f-41c1-afa6-793b41f42035",
        "city": "Bengaluru",
        "timestamp": "2025-08-18T09:48:58.335199",
        "rating": 5,
        "comment": "The new flyover has really eased the **traffic congestion** in the northern part of Bengaluru. A great infrastructure project.",
        "public_service": "Traffic Management",
        "district": "Bengaluru",
        "device_location": "12.9334,77.5577",
        "is_anonymous": False,
        "name": "Zakir Hussain",
        "gender": "Female",
        "age": 29,
        "imgUrl": "https://example.com/images/909080b1-440a-4b50-b9a8-2c799c09fcc1.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "23fb4ecf-c8fe-4a71-92d6-32965c09a8ee",
        "city": "Chennai",
        "timestamp": "2025-08-18T04:44:58.335417",
        "rating": 5,
        "comment": "Thanks to the Chennai **Electricity** team for the quick response during the night-time blackout. Power restored in an hour.",
        "public_service": "Electricity",
        "district": "Chennai",
        "device_location": "13.0855,80.2354",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/1dc3358d-cbbb-43af-a2ba-b9567be9cefd.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "fd0fb0cd-aed1-4254-a6b7-e35503ecaa9a",
        "city": "Kolkata",
        "timestamp": "2025-02-01T15:55:58.335847",
        "rating": 4,
        "comment": "The main road in Kolkata is absolutely riddled with **potholes**. It's a risk for two-wheelers and drivers need to swerve dangerously.",
        "public_service": "Road Maintenance",
        "district": "Kolkata",
        "device_location": "22.5848,88.353",
        "is_anonymous": False,
        "name": "Samrat Ghosh",
        "gender": "Female",
        "age": 52,
        "imgUrl": "https://example.com/images/762e9af0-0112-4a69-9ef9-2491876e9e7d.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "c259ba3e-ae97-4feb-be63-a1ad96e476e7",
        "city": "Chennai",
        "timestamp": "2025-06-05T18:34:58.336108",
        "rating": 4,
        "comment": "The **water quality** in Chennai is poor; it's often muddy and has a strange odour, raising health concerns. Please check for pipeline contamination.",
        "public_service": "Water Supply",
        "district": "Chennai",
        "device_location": "13.0461,80.2902",
        "is_anonymous": False,
        "name": "Rohit Khanna",
        "gender": "Male",
        "age": 39,
        "imgUrl": "https://example.com/images/ca9698dd-2c54-4e27-aa5f-04bf9413ca9d.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "959cbf34-8b67-4562-ad52-6a62d2211ae1",
        "city": "Mumbai",
        "timestamp": "2025-07-06T21:33:58.336327",
        "rating": 4,
        "comment": "We need a public schedule for the **load shedding** in Mumbai. Random power cuts disrupt everything.",
        "public_service": "Electricity",
        "district": "Mumbai",
        "device_location": "19.0318,72.8575",
        "is_anonymous": False,
        "name": "Rohit Khanna",
        "gender": "Other",
        "age": 19,
        "imgUrl": "https://example.com/images/8f8ed0fb-4541-4be5-920a-eefaac6504e1.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "fed64921-b292-4a49-8431-627429bf60d8",
        "city": "Mumbai",
        "timestamp": "2025-04-26T22:28:58.336585",
        "rating": 5,
        "comment": "The new flyover has really eased the **traffic congestion** in the northern part of Mumbai. A great infrastructure project.",
        "public_service": "Traffic Management",
        "district": "Mumbai",
        "device_location": "19.0797,72.9116",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Other",
        "age": 32,
        "imgUrl": "https://example.com/images/9e7fbc98-ad93-4fd6-8f8b-c1841dd591a3.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d3fb67eb-0d9a-4639-94c2-8c36865d9f30",
        "city": "Chennai",
        "timestamp": "2024-11-16T19:19:58.336844",
        "rating": 4,
        "comment": "The level of **overcrowding** is better now in Chennai thanks to the new shared taxi service initiative.",
        "public_service": "Public Transport",
        "district": "Chennai",
        "device_location": "13.1321,80.3201",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/542d1167-ef3a-43e7-b02b-0af497857eca.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "10b6feee-9678-4193-99f7-6f6510d825a2",
        "city": "Mumbai",
        "timestamp": "2025-01-06T17:22:58.337047",
        "rating": 4,
        "comment": "Great work by the **Street Lights** team in Mumbai! The entire stretch of the highway has new, bright, and working lights.",
        "public_service": "Street Lights",
        "district": "Mumbai",
        "device_location": "19.092,72.8294",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/9fd4434c-a4d9-4cc7-a2df-7d1ba721ad60.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "c2731ae0-c667-44e6-8aed-98e3f49f1522",
        "city": "Mumbai",
        "timestamp": "2025-05-30T21:17:58.337275",
        "rating": 5,
        "comment": "The **power supply** has been remarkably stable in Mumbai over the last six months. Excellent job by the Electricity department.",
        "public_service": "Electricity",
        "district": "Mumbai",
        "device_location": "19.0534,72.8607",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/f4636337-0545-4739-b46c-8c3bdf8b185d.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "44aa6ff3-7a70-4ebf-ad13-05aa62d6d9c5",
        "city": "Delhi",
        "timestamp": "2025-07-14T00:36:58.337481",
        "rating": 5,
        "comment": "The **street lights** in the back alleys of Delhi are crucial for safety but are mostly out of order. Please check.",
        "public_service": "Street Lights",
        "district": "Delhi",
        "device_location": "28.6666,77.1289",
        "is_anonymous": False,
        "name": "Aditi Mishra",
        "gender": "Male",
        "age": 19,
        "imgUrl": "https://example.com/images/d52de032-5367-4a21-887e-fc40af0de7ab.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "b6b188e6-069e-4dbf-878d-3e710ecdc9d5",
        "city": "Delhi",
        "timestamp": "2025-06-23T06:07:58.337788",
        "rating": 4,
        "comment": "There's a complete **lack of street lights** on the side lanes in Delhi, making it extremely unsafe to walk at night.",
        "public_service": "Street Lights",
        "district": "Delhi",
        "device_location": "28.6739,77.0604",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/10dc5aee-e921-4a84-ab26-b56f3b06b7be.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "0f9ee34b-9a6a-4689-a175-86a84236be5d",
        "city": "Chennai",
        "timestamp": "2025-04-01T20:01:58.338302",
        "rating": 5,
        "comment": "The **overcrowding** on the buses during office hours in Chennai is dangerous and uncomfortable. Need more buses on peak routes.",
        "public_service": "Public Transport",
        "district": "Chennai",
        "device_location": "13.0451,80.3004",
        "is_anonymous": False,
        "name": "Samrat Ghosh",
        "gender": "Female",
        "age": 51,
        "imgUrl": "https://example.com/images/1433c746-ba7c-4414-904d-842ba06c0345.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "54d83cf6-5225-4cb6-932e-b03559df5120",
        "city": "Kolkata",
        "timestamp": "2025-09-19T11:29:58.338669",
        "rating": 4,
        "comment": "The **traffic signal** at the main crossing in Kolkata has been broken for 3 days, causing massive confusion and near accidents.",
        "public_service": "Traffic Management",
        "district": "Kolkata",
        "device_location": "22.5741,88.3574",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Female",
        "age": 30,
        "imgUrl": "https://example.com/images/34c86e23-8e80-44fc-a0a4-bc05b922b30b.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "9f0ea475-a1c8-4b58-8da5-be5596f366f5",
        "city": "Delhi",
        "timestamp": "2025-05-22T14:06:58.338942",
        "rating": 5,
        "comment": "The level of **overcrowding** is better now in Delhi thanks to the new shared taxi service initiative.",
        "public_service": "Public Transport",
        "district": "Delhi",
        "device_location": "28.737,77.1237",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Male",
        "age": 41,
        "imgUrl": "https://example.com/images/b442061c-af70-4283-8b73-851785c0dc46.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "46105543-b2bf-4bb3-9363-3e544db736df",
        "city": "Kolkata",
        "timestamp": "2024-12-29T06:58:58.339323",
        "rating": 4,
        "comment": "The temporary filling of the **potholes** in Kolkata didn't last a week. We need a proper, permanent solution.",
        "public_service": "Road Maintenance",
        "district": "Kolkata",
        "device_location": "22.613,88.3496",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/5ae60720-7eb0-4198-9e0d-9aa5aed3560f.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "a4371910-831d-4ac1-aa52-3006ea9d3bdc",
        "city": "Hyderabad",
        "timestamp": "2025-01-26T01:35:58.339565",
        "rating": 5,
        "comment": "Thanks to the Hyderabad **Public Transport** service for the prompt and on-schedule journey today. Excellent ride!",
        "public_service": "Public Transport",
        "district": "Hyderabad",
        "device_location": "17.3758,78.4563",
        "is_anonymous": False,
        "name": "Neha Thakur",
        "gender": "Male",
        "age": 25,
        "imgUrl": "https://example.com/images/564ec006-f8ec-4cf3-9083-93c7eea7f2ab.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "30780879-3c99-47cc-b58f-b59b9fe24e09",
        "city": "Chennai",
        "timestamp": "2025-06-05T09:24:58.339752",
        "rating": 4,
        "comment": "The **Street Lights** service has been prompt in repairing the faulty lamps in Chennai. Very quick service.",
        "public_service": "Street Lights",
        "district": "Chennai",
        "device_location": "13.0831,80.3132",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/9e3db205-b333-4579-ab86-0ec9bb2d7581.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d79f1959-67e5-4f86-8728-22644c7b3cff",
        "city": "Kolkata",
        "timestamp": "2025-05-03T06:46:58.339943",
        "rating": 5,
        "comment": "The **garbage collection** in Kolkata has become highly irregular. Sometimes they miss entire weeks, causing huge piles of waste.",
        "public_service": "Garbage Collection",
        "district": "Kolkata",
        "device_location": "22.5321,88.3268",
        "is_anonymous": False,
        "name": "Isha Sharma",
        "gender": "Male",
        "age": 27,
        "imgUrl": "https://example.com/images/ff2f50be-83ef-4df8-b7e4-4471d75eb820.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "e45530bc-3b62-42db-8f59-954e19b6d020",
        "city": "Kolkata",
        "timestamp": "2025-06-22T15:07:58.340184",
        "rating": 4,
        "comment": "Relief! The **contaminated water** issue in Kolkata seems to be resolved. The water is clear again. Appreciate the swift action.",
        "public_service": "Water Supply",
        "district": "Kolkata",
        "device_location": "22.5473,88.341",
        "is_anonymous": False,
        "name": "Isha Sharma",
        "gender": "Male",
        "age": 42,
        "imgUrl": "https://example.com/images/ff691c59-090e-4e2f-bda7-eb97ba3a3a3b.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "8b95e95f-ad89-4c1f-84b0-0b9e9fe1edca",
        "city": "Bengaluru",
        "timestamp": "2024-12-24T05:37:58.340565",
        "rating": 4,
        "comment": "Driving on the highway through Bengaluru is a nightmare because of the constant bumps and **uneven road surfaces**. Please ensure a smooth drive.",
        "public_service": "Road Maintenance",
        "district": "Bengaluru",
        "device_location": "12.9776,77.5719",
        "is_anonymous": False,
        "name": "Suresh Nair",
        "gender": "Male",
        "age": 27,
        "imgUrl": "https://example.com/images/34e283b8-a8d2-45a8-81e8-ed9bb24a84c0.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "92e2abba-c4b8-4214-9342-fcc9a3937900",
        "city": "Ahmedabad",
        "timestamp": "2025-04-29T18:23:58.340801",
        "rating": 4,
        "comment": "The **traffic signal** works perfectly now in Ahmedabad. No more unnecessary waiting periods.",
        "public_service": "Traffic Management",
        "district": "Ahmedabad",
        "device_location": "23.0134,72.5259",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/6ac1af42-9837-4d28-b464-e4b9a364c9ee.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "61a085bc-c362-44e5-a55a-6765d40bfded",
        "city": "Hyderabad",
        "timestamp": "2025-10-24T01:32:58.340992",
        "rating": 4,
        "comment": "The local **dumping ground** near Hyderabad is badly managed. The garbage is strewn everywhere, and stray dogs are a menace.",
        "public_service": "Garbage Collection",
        "district": "Hyderabad",
        "device_location": "17.3585,78.499",
        "is_anonymous": False,
        "name": "Ravi Kumar",
        "gender": "Female",
        "age": 21,
        "imgUrl": "https://example.com/images/6005dcee-7b9d-487e-b5f7-c033c7d57b17.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "c96dae25-9905-4590-878a-51d90ad6b94a",
        "city": "Bengaluru",
        "timestamp": "2025-03-27T20:58:58.341237",
        "rating": 4,
        "comment": "The number of **cancelled buses** on the route to the industrial area of Bengaluru is too high. This must be addressed.",
        "public_service": "Public Transport",
        "district": "Bengaluru",
        "device_location": "12.9916,77.5684",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/3a36ae78-15d2-4fff-8d1f-1c5b6a8b20f9.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "67e6fb43-5e88-4707-a9fd-8f753a48b3d7",
        "city": "Bengaluru",
        "timestamp": "2025-10-12T08:32:58.341431",
        "rating": 4,
        "comment": "The **voltage fluctuations** in Bengaluru are severe, causing my fan to slow down and lights to flicker. I'm worried about my AC.",
        "public_service": "Electricity",
        "district": "Bengaluru",
        "device_location": "12.9248,77.643",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Other",
        "age": 53,
        "imgUrl": "https://example.com/images/8253c767-548a-446e-b071-2696094793d9.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "6c99649d-e547-4c80-a172-f4a3887056b0",
        "city": "Ahmedabad",
        "timestamp": "2025-10-07T05:00:58.341624",
        "rating": 5,
        "comment": "Every evening, precisely at 7 PM, the power goes out in Ahmedabad. The **load shedding** is completely unacceptable.",
        "public_service": "Electricity",
        "district": "Ahmedabad",
        "device_location": "23.0679,72.5775",
        "is_anonymous": False,
        "name": "Neha Thakur",
        "gender": "Female",
        "age": 64,
        "imgUrl": "https://example.com/images/75ea7e4b-1918-4896-80bb-19d7711ca994.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "84dcf731-382b-4025-849a-fa8ca2cfcaca",
        "city": "Ahmedabad",
        "timestamp": "2025-08-08T12:31:58.341850",
        "rating": 5,
        "comment": "There is a major **pipe leak** near the main road in Ahmedabad, leading to huge wastage of water. It's been running for two days.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "23.042,72.5812",
        "is_anonymous": False,
        "name": "Neha Thakur",
        "gender": "Female",
        "age": 49,
        "imgUrl": "https://example.com/images/59a2e8b4-945b-4ee1-8b1b-9a901841f34e.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "b1cfd383-d732-4558-8064-6d638c5d8258",
        "city": "Kolkata",
        "timestamp": "2025-10-07T02:03:58.342075",
        "rating": 4,
        "comment": "The **water quality** in Kolkata is poor; it's often muddy and has a strange odour, raising health concerns. Please check for pipeline contamination.",
        "public_service": "Water Supply",
        "district": "Kolkata",
        "device_location": "22.5422,88.3934",
        "is_anonymous": False,
        "name": "Suresh Nair",
        "gender": "Other",
        "age": 46,
        "imgUrl": "https://example.com/images/56f00536-0a05-4872-ae92-ad8a2affecfc.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "3c8367f6-b1aa-4fe9-bccf-1ea9cadb07e0",
        "city": "Hyderabad",
        "timestamp": "2025-03-06T16:58:58.342294",
        "rating": 5,
        "comment": "A small leak in the main distribution line in Hyderabad is worsening. Please fix the **leaking pipes** before it bursts.",
        "public_service": "Water Supply",
        "district": "Hyderabad",
        "device_location": "17.3781,78.5225",
        "is_anonymous": False,
        "name": "Neha Thakur",
        "gender": "Female",
        "age": 50,
        "imgUrl": "https://example.com/images/28b068b8-4352-4125-945f-2a876ba37d05.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "eeefc6c3-4bf0-43b9-9dbe-813870006e0e",
        "city": "Mumbai",
        "timestamp": "2024-12-26T22:43:58.342531",
        "rating": 4,
        "comment": "Every Friday evening, the **traffic** in Mumbai becomes unbearable. More police deployment is necessary.",
        "public_service": "Traffic Management",
        "district": "Mumbai",
        "device_location": "19.1245,72.8722",
        "is_anonymous": False,
        "name": "Samrat Ghosh",
        "gender": "Other",
        "age": 60,
        "imgUrl": "https://example.com/images/4a874373-c9ff-466e-a4a2-04305a06953f.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "be5ce9c4-9e20-42f4-b4e6-d3f504dd7bb0",
        "city": "Mumbai",
        "timestamp": "2025-01-18T23:43:58.342752",
        "rating": 5,
        "comment": "Relief! The **contaminated water** issue in Mumbai seems to be resolved. The water is clear again. Appreciate the swift action.",
        "public_service": "Water Supply",
        "district": "Mumbai",
        "device_location": "19.0664,72.8797",
        "is_anonymous": False,
        "name": "Vikram Mehta",
        "gender": "Female",
        "age": 65,
        "imgUrl": "https://example.com/images/96ea5c55-dc16-4657-b8f0-df7ab0efdf9c.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "ecccd3c9-f17b-4ff8-a9af-ea25c735f126",
        "city": "Ahmedabad",
        "timestamp": "2025-09-29T22:20:58.342970",
        "rating": 4,
        "comment": "The **water supply** in Ahmedabad has been highly **inconsistent**. We often get water only for a short time in the morning, making it impossible to manage daily chores. A fixed schedule is urgently needed.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "23.012,72.6085",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/52acded2-4a59-4cdb-bf5d-6b700c71a770.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "6c9b7b82-c556-4048-aa47-f5384a73eb09",
        "city": "Chennai",
        "timestamp": "2025-07-15T04:37:58.343166",
        "rating": 5,
        "comment": "We are having **frequent power cuts** (load shedding) in Chennai, sometimes lasting for hours. This severely impacts our work-from-home schedule.",
        "public_service": "Electricity",
        "district": "Chennai",
        "device_location": "13.1151,80.2294",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/16bdd052-5c3a-4570-9e61-6999a8c96f34.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d60970a3-6ec4-4a24-a8e2-0703f6bd1df7",
        "city": "Pune",
        "timestamp": "2025-08-27T02:58:58.343378",
        "rating": 4,
        "comment": "A small leak in the main distribution line in Pune is worsening. Please fix the **leaking pipes** before it bursts.",
        "public_service": "Water Supply",
        "district": "Pune",
        "device_location": "18.4874,73.8487",
        "is_anonymous": False,
        "name": "Arun Roy",
        "gender": "Male",
        "age": 20,
        "imgUrl": "https://example.com/images/819cfede-4a63-4413-967c-05092ce3827a.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "4b9de4be-4fcf-4003-a443-435e88ded904",
        "city": "Bengaluru",
        "timestamp": "2025-09-23T19:41:58.343567",
        "rating": 5,
        "comment": "Great work by the **Street Lights** team in Bengaluru! The entire stretch of the highway has new, bright, and working lights.",
        "public_service": "Street Lights",
        "district": "Bengaluru",
        "device_location": "12.94,77.6353",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Female",
        "age": 35,
        "imgUrl": "https://example.com/images/376e663f-c748-4973-9ade-a2efc0590bce.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "f65ed3c9-7412-45e7-9319-067cd6c1fc71",
        "city": "Kolkata",
        "timestamp": "2025-01-29T15:03:58.343750",
        "rating": 5,
        "comment": "Great work by the **Street Lights** team in Kolkata! The entire stretch of the highway has new, bright, and working lights.",
        "public_service": "Street Lights",
        "district": "Kolkata",
        "device_location": "22.5291,88.34",
        "is_anonymous": False,
        "name": "Divya Menon",
        "gender": "Other",
        "age": 27,
        "imgUrl": "https://example.com/images/e5bc5db6-18f2-4140-acba-77762ab699d9.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "9155b81e-aff1-45be-b4ef-d4bdb2def87a",
        "city": "Delhi",
        "timestamp": "2025-04-05T09:16:58.344142",
        "rating": 4,
        "comment": "The temporary filling of the **potholes** in Delhi didn't last a week. We need a proper, permanent solution.",
        "public_service": "Road Maintenance",
        "district": "Delhi",
        "device_location": "28.6979,77.1403",
        "is_anonymous": False,
        "name": "Kiran Reddy",
        "gender": "Male",
        "age": 50,
        "imgUrl": "https://example.com/images/0a01b4ff-dc3f-4312-8014-a1c86b400165.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "5e20e440-d2b2-4a2e-96b2-f8312f8d15f8",
        "city": "Pune",
        "timestamp": "2024-12-09T07:39:58.344335",
        "rating": 4,
        "comment": "The **Street Lights** service has been prompt in repairing the faulty lamps in Pune. Very quick service.",
        "public_service": "Street Lights",
        "district": "Pune",
        "device_location": "18.4825,73.82",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/99f38208-844a-49dc-bba5-923a66e5c374.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d49fef88-ac1e-4414-9c10-5456bc5d0b3b",
        "city": "Bengaluru",
        "timestamp": "2025-07-13T07:23:58.344585",
        "rating": 4,
        "comment": "I've found the **public transport** in Bengaluru to be highly reliable recently. The bus is always on time, which is a great relief.",
        "public_service": "Public Transport",
        "district": "Bengaluru",
        "device_location": "12.9482,77.5961",
        "is_anonymous": False,
        "name": "Anjali Singh",
        "gender": "Other",
        "age": 22,
        "imgUrl": "https://example.com/images/313af5f4-fe0e-47da-ba24-963baff03398.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d0b8d4a2-23ef-402d-89f8-de0f7cf37b7c",
        "city": "Chennai",
        "timestamp": "2025-07-28T18:47:58.344806",
        "rating": 4,
        "comment": "There is a major **pipe leak** near the main road in Chennai, leading to huge wastage of water. It's been running for two days.",
        "public_service": "Water Supply",
        "district": "Chennai",
        "device_location": "13.1185,80.2371",
        "is_anonymous": False,
        "name": "Aditi Mishra",
        "gender": "Other",
        "age": 56,
        "imgUrl": "https://example.com/images/99fdd78a-0914-4d4a-9fc0-60259bb2d9f6.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "4203e6a0-8e6f-4449-ad29-50ba75ed5485",
        "city": "Hyderabad",
        "timestamp": "2025-10-16T20:45:58.345049",
        "rating": 4,
        "comment": "The new flyover has really eased the **traffic congestion** in the northern part of Hyderabad. A great infrastructure project.",
        "public_service": "Traffic Management",
        "district": "Hyderabad",
        "device_location": "17.3968,78.4696",
        "is_anonymous": False,
        "name": "Priya Verma",
        "gender": "Male",
        "age": 18,
        "imgUrl": "https://example.com/images/8b046374-6260-49a5-9ec0-202219d068b9.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "828e94d5-5702-4bba-86ba-b7a26b38baed",
        "city": "Kolkata",
        "timestamp": "2025-05-10T09:28:58.345306",
        "rating": 4,
        "comment": "The **local trains** are severely **overcrowded** in Kolkata. Can the frequency be increased during the morning rush?",
        "public_service": "Public Transport",
        "district": "Kolkata",
        "device_location": "22.6136,88.3366",
        "is_anonymous": False,
        "name": "Arun Roy",
        "gender": "Female",
        "age": 46,
        "imgUrl": "https://example.com/images/15ea9459-495f-48b7-9308-e9b282616255.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "82606264-2660-41cd-873f-ce63018b2b08",
        "city": "Mumbai",
        "timestamp": "2025-09-09T14:09:58.345499",
        "rating": 5,
        "comment": "Great work by the **Street Lights** team in Mumbai! The entire stretch of the highway has new, bright, and working lights.",
        "public_service": "Street Lights",
        "district": "Mumbai",
        "device_location": "19.0839,72.8388",
        "is_anonymous": False,
        "name": "Divya Menon",
        "gender": "Female",
        "age": 60,
        "imgUrl": "https://example.com/images/7d2bb852-8fd4-4d42-a9a1-7cbbe06b322a.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "31a5d167-fc5c-43ef-84bd-b46b1abafb14",
        "city": "Kolkata",
        "timestamp": "2024-12-25T01:27:58.345695",
        "rating": 4,
        "comment": "The **voltage fluctuations** in Kolkata are severe, causing my fan to slow down and lights to flicker. I'm worried about my AC.",
        "public_service": "Electricity",
        "district": "Kolkata",
        "device_location": "22.5287,88.37",
        "is_anonymous": False,
        "name": "Tarun Bhasin",
        "gender": "Female",
        "age": 27,
        "imgUrl": "https://example.com/images/dbb1abdc-68dc-496e-89be-720aab3102bb.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "3f284710-f929-4297-8640-bb5a59b33347",
        "city": "Bengaluru",
        "timestamp": "2024-12-12T02:19:58.345897",
        "rating": 4,
        "comment": "The local **dumping ground** near Bengaluru is badly managed. The garbage is strewn everywhere, and stray dogs are a menace.",
        "public_service": "Garbage Collection",
        "district": "Bengaluru",
        "device_location": "12.9373,77.5793",
        "is_anonymous": False,
        "name": "Lata Joshi",
        "gender": "Female",
        "age": 52,
        "imgUrl": "https://example.com/images/30c7bb81-3e1c-415b-b675-4df4104c63c7.jpg",
        "imgDesc": "Image showing issue related to garbage collection",
        "imgTag": [
            "garbage collection",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "884934d3-7fab-4bca-8b1b-aadaea7d6af5",
        "city": "Pune",
        "timestamp": "2025-02-03T06:49:58.346342",
        "rating": 5,
        "comment": "We experienced a huge spike in **voltage** last night in Pune. The Electricity department must monitor the line stability.",
        "public_service": "Electricity",
        "district": "Pune",
        "device_location": "18.5153,73.9004",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/4107c79a-3e0f-4d1b-ace2-1d9472de664d.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "6cacb81c-9cad-4055-bc58-58da9d05c94d",
        "city": "Pune",
        "timestamp": "2025-07-31T19:37:58.346891",
        "rating": 4,
        "comment": "For the past week, the **water pressure** has been so low in Pune that our overhead tank barely fills up. Please look into the distribution lines.",
        "public_service": "Water Supply",
        "district": "Pune",
        "device_location": "18.5566,73.8271",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Other",
        "age": 62,
        "imgUrl": "https://example.com/images/91a05696-a262-49bf-b83e-dea47df870a5.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "0d477c58-b38e-44a3-88cd-d34ad945d65d",
        "city": "Chennai",
        "timestamp": "2025-09-03T00:00:58.347304",
        "rating": 5,
        "comment": "The recently maintained roads in the residential areas of Chennai are excellent. A smooth commute, thank you **Road Maintenance**!",
        "public_service": "Road Maintenance",
        "district": "Chennai",
        "device_location": "13.0884,80.2844",
        "is_anonymous": False,
        "name": "Isha Sharma",
        "gender": "Other",
        "age": 56,
        "imgUrl": "https://example.com/images/b9237847-9b8b-4a49-8e28-cb5b836a8ba9.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "86c6c717-6527-468e-a413-37d14ae1e22e",
        "city": "Delhi",
        "timestamp": "2025-07-21T08:06:58.347505",
        "rating": 5,
        "comment": "We experienced a huge spike in **voltage** last night in Delhi. The Electricity department must monitor the line stability.",
        "public_service": "Electricity",
        "district": "Delhi",
        "device_location": "28.7106,77.1334",
        "is_anonymous": False,
        "name": "Sneha Patel",
        "gender": "Female",
        "age": 54,
        "imgUrl": "https://example.com/images/e2e25759-b877-4e3d-a503-6e4426350beb.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1eb6a467-8f7a-489c-a012-5ea9ff2bee5d",
        "city": "Ahmedabad",
        "timestamp": "2025-01-10T10:25:58.347697",
        "rating": 5,
        "comment": "It's shocking how many **non-functional street lights** there are on the main bypass road in Ahmedabad. Please replace them.",
        "public_service": "Street Lights",
        "district": "Ahmedabad",
        "device_location": "23.0666,72.5281",
        "is_anonymous": False,
        "name": "Manoj Iyer",
        "gender": "Other",
        "age": 28,
        "imgUrl": "https://example.com/images/00e2305c-408e-46e3-8224-c0054b6b4f0f.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1d5f71ab-1559-4043-a033-fdd03d1e1e88",
        "city": "Bengaluru",
        "timestamp": "2025-01-19T07:22:58.348081",
        "rating": 5,
        "comment": "The temporary filling of the **potholes** in Bengaluru didn't last a week. We need a proper, permanent solution.",
        "public_service": "Road Maintenance",
        "district": "Bengaluru",
        "device_location": "12.9827,77.6071",
        "is_anonymous": False,
        "name": "Suresh Nair",
        "gender": "Other",
        "age": 65,
        "imgUrl": "https://example.com/images/f54c7aa1-24b4-4370-b384-500ab1213e71.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "8cb2ae37-fae3-4ec4-94a9-7dd3721f01af",
        "city": "Delhi",
        "timestamp": "2025-07-21T20:07:58.348474",
        "rating": 4,
        "comment": "Near the market area, the road is broken and full of **potholes**. It looks like a crater field! Urgently needs resurfacing in Delhi.",
        "public_service": "Road Maintenance",
        "district": "Delhi",
        "device_location": "28.6885,77.1458",
        "is_anonymous": False,
        "name": "Gaurav Jain",
        "gender": "Female",
        "age": 22,
        "imgUrl": "https://example.com/images/794a4b58-7103-4d7d-ab3a-23b75785b40b.jpg",
        "imgDesc": "Image showing issue related to road maintenance",
        "imgTag": [
            "road maintenance",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "71a6eef4-5830-45e9-abae-c8512bfbfc36",
        "city": "Ahmedabad",
        "timestamp": "2025-03-04T18:34:58.348716",
        "rating": 4,
        "comment": "Relief! The **contaminated water** issue in Ahmedabad seems to be resolved. The water is clear again. Appreciate the swift action.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "22.9832,72.5498",
        "is_anonymous": False,
        "name": "Meera Hegde",
        "gender": "Male",
        "age": 52,
        "imgUrl": "https://example.com/images/e1460675-0763-4ab3-bf8f-4d7328151847.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "ad50ba8e-61e6-45b9-b2d0-99d5c9420d78",
        "city": "Ahmedabad",
        "timestamp": "2025-02-13T19:52:58.348961",
        "rating": 4,
        "comment": "The **water quality** in Ahmedabad is poor; it's often muddy and has a strange odour, raising health concerns. Please check for pipeline contamination.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "23.066,72.6115",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/7a0a8253-b0a1-4ca7-8bed-af564191af74.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 2,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "79b15ec9-7456-425d-923d-98a0c5e104b5",
        "city": "Bengaluru",
        "timestamp": "2024-12-31T21:15:58.349173",
        "rating": 5,
        "comment": "I appreciate the **Electricity** board for reducing the duration of **power cuts** in Bengaluru. Much more stable now.",
        "public_service": "Electricity",
        "district": "Bengaluru",
        "device_location": "13.003,77.6091",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/1d7f1610-8dbc-4f71-8c2e-4472f88a6837.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "7fd2bc3b-0aa8-49a1-88c6-d96de260d33e",
        "city": "Ahmedabad",
        "timestamp": "2025-01-26T07:55:58.349368",
        "rating": 4,
        "comment": "The **non-functional lights** are a huge issue in Ahmedabad. Walking home after dark feels very dangerous now.",
        "public_service": "Street Lights",
        "district": "Ahmedabad",
        "device_location": "23.0065,72.5912",
        "is_anonymous": False,
        "name": "Deepa Das",
        "gender": "Female",
        "age": 45,
        "imgUrl": "https://example.com/images/0df7ea32-396e-4c87-b170-bab26bf1b3ec.jpg",
        "imgDesc": "Image showing issue related to street lights",
        "imgTag": [
            "street lights",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "13d791ed-bc72-42be-8c71-376bc5af5cce",
        "city": "Bengaluru",
        "timestamp": "2025-03-07T20:13:58.349617",
        "rating": 5,
        "comment": "The new fleet of buses in Bengaluru is excellent, but the **timings need to be strictly followed**.",
        "public_service": "Public Transport",
        "district": "Bengaluru",
        "device_location": "12.9595,77.6353",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/9078a31c-aca5-4bae-a1c8-83941f8838ef.jpg",
        "imgDesc": "Image showing issue related to public transport",
        "imgTag": [
            "public transport",
            "city issue"
        ],
        "imgSeverity": 5,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "dd920b11-844e-4c92-b95d-dec245d3bd8b",
        "city": "Ahmedabad",
        "timestamp": "2024-11-18T00:35:58.349817",
        "rating": 4,
        "comment": "Thanks to the Ahmedabad **Electricity** team for the quick response during the night-time blackout. Power restored in an hour.",
        "public_service": "Electricity",
        "district": "Ahmedabad",
        "device_location": "22.9978,72.5761",
        "is_anonymous": False,
        "name": "Sneha Patel",
        "gender": "Female",
        "age": 62,
        "imgUrl": "https://example.com/images/6e2cae77-a13e-4b30-a672-403cefd3c4c7.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 3,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "3e3e2cb7-351f-40d3-bbdc-986015141d6c",
        "city": "Ahmedabad",
        "timestamp": "2024-11-17T08:10:58.350042",
        "rating": 5,
        "comment": "For the past week, the **water pressure** has been so low in Ahmedabad that our overhead tank barely fills up. Please look into the distribution lines.",
        "public_service": "Water Supply",
        "district": "Ahmedabad",
        "device_location": "22.997,72.5495",
        "is_anonymous": False,
        "name": "Rohit Khanna",
        "gender": "Other",
        "age": 35,
        "imgUrl": "https://example.com/images/6abbaad9-b711-491e-a3e3-2701744192ee.jpg",
        "imgDesc": "Image showing issue related to water supply",
        "imgTag": [
            "water supply",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "1ae49d75-a07c-48b4-85b7-cee1875b5147",
        "city": "Ahmedabad",
        "timestamp": "2025-03-17T09:47:58.350280",
        "rating": 5,
        "comment": "Every Friday evening, the **traffic** in Ahmedabad becomes unbearable. More police deployment is necessary.",
        "public_service": "Traffic Management",
        "district": "Ahmedabad",
        "device_location": "23.055,72.5257",
        "is_anonymous": True,
        "name": None,
        "gender": None,
        "age": None,
        "imgUrl": "https://example.com/images/32c65d11-dec9-4ddd-b6bc-5293d357b14a.jpg",
        "imgDesc": "Image showing issue related to traffic management",
        "imgTag": [
            "traffic management",
            "city issue"
        ],
        "imgSeverity": 4,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    },
    {
        "id": "d8ea37ef-3ce9-4661-8314-3d1da31bb2d4",
        "city": "Hyderabad",
        "timestamp": "2025-04-08T02:42:58.350476",
        "rating": 5,
        "comment": "We experienced a huge spike in **voltage** last night in Hyderabad. The Electricity department must monitor the line stability.",
        "public_service": "Electricity",
        "district": "Hyderabad",
        "device_location": "17.3713,78.483",
        "is_anonymous": False,
        "name": "Ayesha Khan",
        "gender": "Female",
        "age": 58,
        "imgUrl": "https://example.com/images/a5b7370e-89a9-44b4-9031-81dd38f946dd.jpg",
        "imgDesc": "Image showing issue related to electricity",
        "imgTag": [
            "electricity",
            "city issue"
        ],
        "imgSeverity": 1,
        "cleaned_comment": None,
        "_model_output": None,
        "processing": 0
    }
]


def send_report(report):
    try:
        response = requests.post(API_URL, json=report)

        # ensure request completed successfully
        response.raise_for_status()

        print(f"✅ Sent report for city: {report['city']}")
        print("Response:", response.json())

    except Exception as e:
        print(f"❌ Error sending report for {report['city']}:", e)
        # stop script if one fails (like await)
        raise e  


def main():
    for report in reports_data:
        send_report(report)  # 🚀 Request only goes AFTER previous finishes


if __name__ == "__main__":
    main()
